export const exec_planner_data = [
  {
    id: 1,
    store_code: "500003",
    chain: "KJ FAIRMART",
    brand: "FONTERRA",
    a5_POSM: "",
    channel: "SECONDARY ACCOUNTS",
    duration_from: "07/01/2025",
    duration_to: "07/31/2025",
    date_uploaded: "06/30/2025",
    uploaded_by: "111361",
    check_1: 0,
    check_2: 0,
    remarks: "",
    tl_name: "",
    tds_name: "HOMER DELA CRUZ",
    employee_id: "TDS-160",
    c2_ActualPictureLink: "",
    activity: "ANLENE 5X 300GX2",
    manager: "MA. JOELITA PANUGALING",
    add_column: "",
    store_class: "",
    tds_group: "GROUP 1",
    tl_1: "JOHANNA CATALUÑA",
    tl_2: "",
    area: "NEGROS OCCIDENTAL",
    city: "NGC-BACOLOD CITY",
    region: "WEST VISAYAS",
    position: "TDS",
    permit_link: "",
    points: "0",
    type_of_ep: "NATIONAL",
    type_of_activity: "PROMO JAN-JULY",
    group_id: "GROUP 1",
    sold_street: "AVA BLDG. GATUSLAO - SAN SEBASTIAN",
    channel_merch: "PROVINCIAL CARRY ALL",
    ep_source: "MARKETING",
    camera_only: "1",
    check_2_remarks: "",
  },
];
